### ISSUE TITLE
Doesn't run anymore on current Ubuntu / Debian Linux versions

### ISSUE THREAD

**Issue by ByteProject** [heasm66/ZAbbrevMaker#7]
![image](https://github.com/heasm66/ZAbbrevMaker/assets/153544/e5e97ac4-a129-42af-846f-07a23ce1331d)

The software has been compiled against libSSL. When you try to launch ZAbbrevMaker on a current Debian based distribution, it refuses to run. It says no suitable SSL version has been found, even though libSSL3 is installed by default on the system. This is unfortunately not easy to fix since older versions of the SSL library are now deprecated on Ubuntu and other Debian based systems. 

I suspect the code needs to be compiled from Visual Studio on Windows, so I am not able to fix it with a new compilation myself.

**Comment by ByteProject** [comment]
The question arises if the software has to be linked to libSSL at all.

**Comment by heasm66** [comment]
It's compiled with Visual Studio 2019 and .NET 6.0. I guess the problems could be resolved by compiling with a newest version, Visual Studio 2022 and an updated .NET 6.0 (.NET 7.0). Unfortunately I'm currently at my summer house and I don't have access to my build computer for another couple of weeks...

To my knowledge ZAbbrevMaker in itself don't use libSSL but the connection probably is somewhere inside the .NET library.

**Comment by heasm66** [comment]
Recompiled with Visual Studio 2022 and NET7.0. I also made some code cleanup and some compile optimization that makes the files smaller and faster (version 0.9 is more than twice as fast as earlier versions).
